from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel

# ==========================================
# Shared Sub-Models
# ==========================================

class Insight(BaseModel):
    title: str
    description: str
    severity: str


class ChartPoint(BaseModel):
    """Structures individual historical trend coordinates for the frontend."""
    month: str
    baseCase: float
    stressScenario: float


# ==========================================
# Dataset Analysis Response
# ==========================================

class DatasetAnalysisResponse(BaseModel):
    filename: str
    dataset_type: str
    business_domain: str
    executive_summary: str
    trend_metrics: List[str]
    trend_data: List[Dict[str, Any]]
    kpis: Dict[str, Any]
    risks: List[str]
    opportunities: List[str]
    insights: List[Insight]


# ==========================================
# Chat Schema
# ==========================================

class ChatQuery(BaseModel):
    """AI CFO chat request."""
    question: str
    context: Optional[Dict[str, Any]] = None


# ==========================================
# Scenario Simulation & Results
# ==========================================

class ScenarioBase(BaseModel):
    inflation_rate: float
    inventory_increase: float
    wage_increase: float
    payment_terms: int
    sales_growth: float


class ScenarioCreate(ScenarioBase):
    scenario_name: str


class ScenarioResponse(ScenarioCreate):
    id: int
    created_at: datetime
    resulting_runway: int
    risk_level: str

    class Config:
        from_attributes = True


# --- ADD THIS NEW BLOCK TO FIX THE ATTRIBUTE ERROR ---
class SimulationResult(BaseModel):
    """Validates and serializes the calculations generated by the stress engine."""
    cash_on_hand: float
    cash_runway_base: int
    cash_runway_stress: int
    gross_margin: float
    burn_rate: float
    working_capital: float
    chart_data: List[ChartPoint]
    risk_level: str
